import Head from 'next/head'

import { Inter } from '@next/font/google'

import Navbar from "../components/Navbar";
import NavBottom from '@/components/NavBottom';

import Screen from '@/components/Screen';
import Footer from '@/components/Footer';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>camazon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
         <Navbar/>
         <NavBottom/>
      </header>
      <main className='bg-gray-200'>
         <Screen/>
      </main>
      <footer>
         <Footer/>
      </footer>
    </>
  )
}
